/** Localização (registro em `Setor`) → setor funcional. Nomes exatamente como no cadastro HEF. */
export const MAPEAMENTO_LOCALIZACAO_SETOR: Array<{ localizacao: string; setor: string }> = [
  { localizacao: "3º Andar - Q301", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q302", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q304", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q309", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q312", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q313", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q314", setor: "Internação - 3º Andar" },
  { localizacao: "3º Andar - Q315", setor: "Internação - 3º Andar" },
  { localizacao: "Isolamento 3º Andar", setor: "Internação - 3º Andar" },
  { localizacao: "Sala Equipamentos 3º Andar", setor: "Internação - 3º Andar" },
  { localizacao: "Q401", setor: "Internação - 4º Andar" },
  { localizacao: "Q402", setor: "Internação - 4º Andar" },
  { localizacao: "Q403", setor: "Internação - 4º Andar" },
  { localizacao: "Q409", setor: "Internação - 4º Andar" },
  { localizacao: "Q410", setor: "Internação - 4º Andar" },
  { localizacao: "Q411", setor: "Internação - 4º Andar" },
  { localizacao: "Q412", setor: "Internação - 4º Andar" },
  { localizacao: "Q413", setor: "Internação - 4º Andar" },
  { localizacao: "Q414", setor: "Internação - 4º Andar" },
  { localizacao: "Q415", setor: "Internação - 4º Andar" },
  { localizacao: "Sala Equipamentos 4º Andar", setor: "Internação - 4º Andar" },
  { localizacao: "Ambulatório", setor: "Ambulatório" },
  { localizacao: "Audiometria", setor: "Ambulatório" },
  { localizacao: "Eletrocardio", setor: "Ambulatório" },
  { localizacao: "Eletroneuro", setor: "Ambulatório" },
  { localizacao: "Ergonometrico", setor: "Ambulatório" },
  { localizacao: "Ultrassom 01", setor: "Ambulatório" },
  { localizacao: "Ultrassom 02", setor: "Ambulatório" },
  { localizacao: "Centro Cirurgico Ambulatorial Sala 01", setor: "Centro Cirúrgico Ambulatorial" },
  { localizacao: "Centro Cirurgico Ambulatorial Sala 02", setor: "Centro Cirúrgico Ambulatorial" },
  { localizacao: "Centro Cirurgico Ambulatorial Sala 03", setor: "Centro Cirúrgico Ambulatorial" },
  { localizacao: "Sala R.P.A. CCA", setor: "Centro Cirúrgico Ambulatorial" },
  { localizacao: "Centro Cirurgico Sala 1", setor: "Centro Cirúrgico" },
  { localizacao: "Centro Cirurgico Sala 2", setor: "Centro Cirúrgico" },
  { localizacao: "Centro Cirurgico Sala 3", setor: "Centro Cirúrgico" },
  { localizacao: "Centro Cirurgico Sala 4", setor: "Centro Cirúrgico" },
  { localizacao: "Centro Cirurgico Sala 5", setor: "Centro Cirúrgico" },
  { localizacao: "Centro Cirurgico Sala 6", setor: "Centro Cirúrgico" },
  { localizacao: "C.M.E.", setor: "CME" },
  { localizacao: "Colonoscopia", setor: "Endoscopia" },
  { localizacao: "Endoscopia", setor: "Endoscopia" },
  { localizacao: "Depósito Equipamentos Eng. Clin.", setor: "Engenharia Clínica" },
  { localizacao: "Emergencia Adulto", setor: "Emergência Adulto" },
  { localizacao: "P.A. Adulto", setor: "Emergência Adulto" },
  { localizacao: "Isolamento Adulto", setor: "Emergência Adulto" },
  { localizacao: "Emergencia Infantil", setor: "Emergência Infantil" },
  { localizacao: "P.A. Infantil", setor: "Emergência Infantil" },
  { localizacao: "Isolamento Infantil", setor: "Emergência Infantil" },
  { localizacao: "Farmácia", setor: "Farmácia" },
  { localizacao: "Hospital Dia", setor: "Hospital Dia" },
  { localizacao: "Sala Equipamentos (Hosp. Dia)", setor: "Hospital Dia" },
  { localizacao: "Laboratório", setor: "Laboratório" },
  { localizacao: "Nutrição", setor: "Nutrição" },
  { localizacao: "Preparo/Recuperação Raio X", setor: "Diagnóstico por Imagem" },
  { localizacao: "Raio X Sala 01", setor: "Diagnóstico por Imagem" },
  { localizacao: "Raio X Sala 02", setor: "Diagnóstico por Imagem" },
  { localizacao: "Tomografia", setor: "Diagnóstico por Imagem" },
  { localizacao: "Sala Hemodinâmica", setor: "Hemodinâmica" },
  { localizacao: "Sala Procedimentos Térreo", setor: "Térreo" },
  { localizacao: "Térreo", setor: "Térreo" },
  { localizacao: "U.T.I.", setor: "UTI" },
  { localizacao: "U.T.I. - Expurgo", setor: "UTI" },
  { localizacao: "U.T.I. - Isolamento", setor: "UTI" },
  { localizacao: "Sala Equipamentos UTI", setor: "UTI" },
];

export const NOMES_SETORES_FUNCIONAIS = [...new Set(MAPEAMENTO_LOCALIZACAO_SETOR.map((m) => m.setor))];
